FROM python:3.14-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN pip install --no-cache-dir uv

COPY ml_core /app/ml_core
COPY workers/tracker /app/workers/tracker

WORKDIR /app/workers/tracker

RUN uv sync --frozen --no-dev --extra gpu

CMD ["uv", "run", "--frozen", "--no-dev", "--extra", "gpu", "faststream", "run", "src.main:app"]
