name: Build and Push to Docker Hub

on:
    push:
        branches:
            - master
            - dev

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push Frontend
              uses: docker/build-push-action@v4
              with:
                  context: ./frontend
                  push: true
                  tags: lniki/track-anything-frontend:latest

            - name: Build and push Gateway
              uses: docker/build-push-action@v4
              with:
                  context: ./gateway
                  push: true
                  tags: lniki/track-anything-gateway:latest

            - name: Build and push Preview
              uses: docker/build-push-action@v4
              with:
                  context: ./
                  file: ./Dockerfile.preview
                  push: true
                  tags: lniki/track-anything-preview-worker:latest

            - name: Build and push Tracker CPU
              uses: docker/build-push-action@v4
              with:
                  context: ./
                  file: ./Dockerfile.tracker
                  push: true
                  tags: lniki/track-anything-tracker-worker-cpu:latest

            - name: Build and push Tracker GPU
              uses: docker/build-push-action@v4
              with:
                  context: ./
                  file: ./Dockerfile.tracker.gpu
                  push: true
                  tags: lniki/track-anything-tracker-worker-gpu:latest
